# Generated by Django 5.2.10 on 2026-06-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('school_admin', 'School Admin'), ('principal', 'Principal'), ('teacher', 'Teacher'), ('bursary', 'Bursary'), ('student', 'Student'), ('parent', 'Parent')], default='school_admin', max_length=20),
        ),
    ]
