# Generated by Django 5.2.17 on 2026-09-10 11:25

import django.db.models.deletion
import fernet_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('admission_no_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('guardian_name', fernet_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True)),
                ('guardian_phone', fernet_fields.fields.EncryptedCharField(blank=True, max_length=20, null=True)),
                ('guardian_email', fernet_fields.fields.EncryptedEmailField(blank=True, max_length=254, null=True)),
                ('student_status', models.CharField(default='active', max_length=20)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.class')),
                ('school', models.ForeignKey(blank=True, help_text='Denormalized from user.school for direct querying', null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
