# Generated by Django 5.2.10 on 2026-06-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeitem',
            name='arm',
            field=models.CharField(blank=True, help_text='e.g. A — combine with year_group for arm-specific fees (e.g. SS A classes)', max_length=10, null=True),
        ),
    ]
