# Generated by Django 5.2.10 on 2026-06-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeitem',
            name='year_group',
            field=models.CharField(blank=True, help_text='e.g. JSS1 — applies to all students in this year group regardless of arm', max_length=20, null=True),
        ),
    ]
