# Generated by Django 5.2.10 on 2026-06-02 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feeitem_year_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeinvoice',
            name='fee_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.feeitem'),
        ),
    ]
