# Generated by Django 5.2.10 on 2026-06-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feeitem_arm'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeitem',
            name='arm_pricing',
            field=models.JSONField(blank=True, help_text='{"A": 85000, "B": 75000} — overrides amount per arm', null=True),
        ),
    ]
