# Generated by Django 5.2.10 on 2026-06-02 06:05

import django.db.models.deletion
from django.db import migrations, models
from decimal import Decimal


def consolidate_invoice_items(apps, schema_editor):
    FeeInvoice = apps.get_model('fees', 'FeeInvoice')
    FeeInvoiceItem = apps.get_model('fees', 'FeeInvoiceItem')

    # Group invoices by (school_id, student_id)
    groups = {}
    for inv in FeeInvoice.objects.all().order_by('created_at'):
        key = (inv.school_id, inv.student_id)
        groups.setdefault(key, []).append(inv)

    for (school_id, student_id), invoices in groups.items():
        # Use the first invoice as the header
        header = invoices[0]
        for inv in invoices:
            FeeInvoiceItem.objects.create(
                invoice=header,
                fee_item=inv.fee_item,
                amount_due=inv.amount_due,
                amount_paid=Decimal('0.00'),
            )
            if inv.pk != header.pk:
                # Accumulate amounts on header
                header.amount_due += inv.amount_due
                header.amount_paid += inv.amount_paid
                inv.delete()
        # Recalculate header status
        if header.amount_paid >= header.amount_due and header.amount_due > 0:
            header.status = 'paid'
        elif header.amount_paid > 0:
            header.status = 'partial'
        else:
            header.status = 'unpaid'
        # Clear fee_item on header (no longer single-item)
        if invoices:
            header.fee_item = None
        header.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_feeinvoice_fee_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fee_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.feeitem')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.feeinvoice')),
            ],
        ),
        migrations.RunPython(consolidate_invoice_items, migrations.RunPython.noop),
    ]
