# Generated by Django 5.2.10 on 2026-06-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_feeitem_arm_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeitem',
            name='arm_pricing',
        ),
        migrations.AddField(
            model_name='feeitem',
            name='pricing_tiers',
            field=models.JSONField(blank=True, help_text='{"JSS1": 45000, "JSS2": 50000} — overrides amount per year_group', null=True),
        ),
    ]
