# Generated by Django 5.2.10 on 2026-06-03 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('year_group', models.CharField(blank=True, max_length=20, null=True)),
                ('arm', models.CharField(blank=True, max_length=10, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'classes',
                'ordering': ('year_group', 'arm'),
                'constraints': [models.UniqueConstraint(fields=('school', 'name'), name='unique_class_per_school')],
            },
        ),
    ]
