# Generated by Django 5.2.10 on 2026-06-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('schools', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ('year_group', 'arm'), 'verbose_name_plural': 'classes'},
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_class_per_school'),
        ),
    ]
