# Generated by Django 5.2.10 on 2026-06-03 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('ca1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ca2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assignment', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exam', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.subject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'term', 'academic_year')},
            },
        ),
    ]
