# Generated by Django 5.2.10 on 2026-06-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_break_model_refactor'),
        ('grades', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'term', 'academic_year')},
        ),
    ]
