# Generated by Django 5.2.10 on 2026-06-03 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0), help_text='First period start time'),
        ),
    ]
