# Generated by Django 5.2.10 on 2026-06-02 07:18

import django.db.models.deletion
from django.db import migrations, models


def populate_year_group(apps, schema_editor):
    Subject = apps.get_model('exams', 'Subject')
    Class = apps.get_model('classes', 'Class')
    for sub in Subject.objects.select_related('class_group').all():
        if sub.class_group:
            sub.year_group = sub.class_group.year_group
            sub.save()
        else:
            sub.year_group = None
            sub.save()


def deduplicate_subjects(apps, schema_editor):
    Subject = apps.get_model('exams', 'Subject')
    Grade = apps.get_model('grades', 'Grade')

    seen = {}
    to_delete = []
    for sub in Subject.objects.all().order_by('id'):
        key = (sub.school_id, sub.name, sub.year_group)
        if key in seen:
            keep = seen[key]
            # Re-point any grades from duplicate to kept subject
            Grade.objects.filter(subject=sub).update(subject=keep)
            to_delete.append(sub.id)
        else:
            seen[key] = sub

    Subject.objects.filter(id__in=to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='year_group',
            field=models.CharField(blank=True, help_text='e.g. SS1 — available to all classes in this year group', max_length=20, null=True),
        ),
        migrations.RunPython(populate_year_group, migrations.RunPython.noop),
        migrations.RunPython(deduplicate_subjects, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='subject',
            name='class_group',
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'name', 'year_group')},
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.subject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'academic_year')},
            },
        ),
    ]
