# Generated by Django 5.2.10 on 2026-06-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_timetable_start_time'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='time_limit_enforced',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='late_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examsession',
            name='question_order',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='unique_exam_student'),
        ),
    ]
