# Generated by Django 5.2.10 on 2026-06-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_timetable_reportcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='break_duration',
            field=models.IntegerField(default=5, help_text='Minutes between periods'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period_count',
            field=models.IntegerField(default=8, help_text='Number of periods per day'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period_duration',
            field=models.IntegerField(default=40, help_text='Minutes per period'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(default='08:00', help_text='First period start time'),
        ),
    ]
