# Generated by Django 5.2.10 on 2026-06-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_grading_and_timetable_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='long_break_after_period',
            field=models.IntegerField(default=0, help_text='Period number after which long break occurs (0 = no long break)'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='long_break_duration',
            field=models.IntegerField(default=0, help_text='Long break duration in minutes'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='break_duration',
            field=models.IntegerField(default=5, help_text='Short break minutes between periods'),
        ),
    ]
