# Generated by Django 5.2.10 on 2026-06-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_long_break_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='break_duration',
        ),
        migrations.AddField(
            model_name='timetable',
            name='short_break_after_period',
            field=models.IntegerField(default=0, help_text='Period after which short break occurs (0 = none)'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='short_break_duration',
            field=models.IntegerField(default=10, help_text='Short break minutes'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='long_break_after_period',
            field=models.IntegerField(default=0, help_text='Period after which long break occurs (0 = none)'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='long_break_duration',
            field=models.IntegerField(default=0, help_text='Long break minutes'),
        ),
    ]
