# Generated by Django 5.2.10 on 2026-06-03 09:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('accent_color', models.CharField(default='#1A7A4A', max_length=7)),
                ('address', models.TextField(blank=True, null=True)),
                ('lga', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('school_type', models.CharField(blank=True, max_length=100, null=True)),
                ('proprietor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('proprietor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('current_term', models.CharField(default='1st Term', max_length=50)),
                ('current_academic_year', models.CharField(default='2025/2026', max_length=20)),
                ('plan', models.CharField(default='trial', max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_ca1', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_ca2', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_assignment', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_exam', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('grade_boundaries', models.JSONField(default=list, help_text='[{"name":"A1","min_pct":75},...]')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_config', to='schools.school')),
            ],
            options={
                'verbose_name': 'Grading Configuration',
            },
        ),
    ]
