# Generated by Django 5.2.10 on 2026-06-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('accent_color', models.CharField(default='#1A7A4A', max_length=7)),
                ('address', models.TextField(blank=True, null=True)),
                ('lga', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('school_type', models.CharField(blank=True, max_length=100, null=True)),
                ('proprietor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('proprietor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('plan', models.CharField(default='trial', max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
