# Generated by Django 5.2.10 on 2026-06-02 07:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_ca1', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_ca2', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_assignment', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_exam', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('grade_boundaries', models.JSONField(default=list, help_text='[{"name":"A1","min_pct":75},...]')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_config', to='schools.school')),
            ],
            options={
                'verbose_name': 'Grading Configuration',
            },
        ),
    ]
