# Generated by Django 5.2.10 on 2026-06-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_grading_and_timetable_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='current_academic_year',
            field=models.CharField(default='2025/2026', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='current_term',
            field=models.CharField(default='1st Term', max_length=50),
        ),
    ]
